// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwRN0Qnhhnssq4M46SORtOGBFRntPgUTQ',
    appId: '1:840321672043:web:29e3af0f84086ca736e22e',
    messagingSenderId: '840321672043',
    projectId: 'swift-app09',
    authDomain: 'swift-app09.firebaseapp.com',
    databaseURL: 'https://swift-app09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-app09.firebasestorage.app',
    measurementId: 'G-5NL5JQPK2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrkPf1FJvx_ZxGEQB4HsfAnTZAXmKzgs',
    appId: '1:840321672043:android:2aed0dcd23a1c58636e22e',
    messagingSenderId: '840321672043',
    projectId: 'swift-app09',
    databaseURL: 'https://swift-app09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-app09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKbCKP0YC8zkG0b3-HKdSQUv3J4X2yQqo',
    appId: '1:840321672043:ios:e3e13421657ff1b636e22e',
    messagingSenderId: '840321672043',
    projectId: 'swift-app09',
    databaseURL: 'https://swift-app09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-app09.firebasestorage.app',
    iosBundleId: 'com.busfleetmanagementsideapp.swift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKbCKP0YC8zkG0b3-HKdSQUv3J4X2yQqo',
    appId: '1:840321672043:ios:e3e13421657ff1b636e22e',
    messagingSenderId: '840321672043',
    projectId: 'swift-app09',
    databaseURL: 'https://swift-app09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-app09.firebasestorage.app',
    iosBundleId: 'com.busfleetmanagementsideapp.swift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwRN0Qnhhnssq4M46SORtOGBFRntPgUTQ',
    appId: '1:840321672043:web:5fd150735f4845de36e22e',
    messagingSenderId: '840321672043',
    projectId: 'swift-app09',
    authDomain: 'swift-app09.firebaseapp.com',
    databaseURL: 'https://swift-app09-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swift-app09.firebasestorage.app',
    measurementId: 'G-LNPSXPSG5W',
  );
}
